### PR TITLE
initial support for m5stack

### PR DESCRIPTION
**Pull request by reaper7**
currently only graphics, without m5stack physical buttons

### CODE REVIEW

**Comment by ImpulseAdventure** [comment]
Thanks @reaper7 for integrating support for the **m5stack**! Note that I intend to consolidate the configuration strategy slightly (Arduino & ESP into `GUIslice_config_ard.h`), but I think the majority of your changes should still remain intact. I will merge the PR after re-testing the existing modes (I don't have an m5stack yet to test with directly).

**Comment by ImpulseAdventure** [comment]
I noticed that there is an `#ifdef` check for `ARDUINO_M5Stack-Core-ESP32`. This throws an error/warning in the Arduino IDE as I understand that hyphens are not valid characters for macro names. I wasn't able to locate where this macro was being defined in an external library -- is there a possibility of renaming it (eg. to `ARDUINO_M5Stack_Core_ESP32`)?

**Comment by reaper7** [comment]
I know about hyphens but only this def is propertly detected by arduino (1.8.5 and 1.9.0beta) on win.
I got this from boards.txt
```
m5stack-core-esp32.build.board=M5Stack-Core-ESP32
```

**Comment by ImpulseAdventure** [comment]
Thanks... yes, it looks like the `build.board` in `arduino-esp32/boards.txt` should probably have avoided hyphens.

To my knowledge, the Arduino IDE will just throw a warning and disregard anything including/after the hyphen (since it treats the remainder as an extra token), so you would probably find that `#ifdef ARDUINO_M5Stack` might still match your existing `boards.txt`, but this isn't particularly clean.

Perhaps the best may be to leave the automation out of the config since most users will still require some pin/feature customization anyway.

**Comment by reaper7** [comment]
done

**Pull request merged**
