### PR TITLE
added support for adafruit feather tft using tsc2007 touch

### PR DESCRIPTION
**Pull request by Pconti31**
Adafruit's 3.5 featherwing V2 uses the TSC2007 touch chip instead of the discontinued STMPE811 touchscreen controller.   The screen and micro SD card are the same but our touchscreen code will needed to be updated.

### CODE REVIEW

**Comment by ImpulseAdventure** [comment]
Finally got back online :)
Thanks @Pconti31 for adding the support for the tsc2007!

Looking at the mods, I'm wondering if it might be a worthwhile to preserve the original feather model config and instead move the updated touch config into an "adafruit_35_feather_touch_v2.h"? Those with the v1 devices would probably find it easier to select a standalone config. What do you think?

**Comment by Pconti31** [comment]
@ImpulseAdventure The reason I didn't is because they no longer manufacture the STMPE811 controller.  However, I see your point.  Adding a new config file is likely the best way to go.  I'll make the mod to my branch to ease the merger.
Paul--

**Comment by Pconti31** [comment]
@ImpulseAdventure Sorry, seems I can't do pushes anymore.
 ! [remote rejected] pconti-FeatherWing-v2 -> pconti-FeatherWing-v2 (push declined due to email privacy restrictions)
error: failed to push some refs to 'github.com:Pconti31/GUIslice.git'
I have no idea what is going on...
Paul--

**Comment by Pconti31** [comment]
@ImpulseAdventure Nevermind, I found the issue and fixed it.

**Comment by ImpulseAdventure** [comment]
Migrated Paul's PR with squashed commits into PR #551, so this can now be closed (as merged).

**Pull request closed without merging**
