### PR TITLE
8bit Mode/Res. Touch/Screen/PROGMEM Elements

### PR DESCRIPTION
**Pull request by nanokatz**
This commits adds
ILI9341 8Bit Mode
Simple Resistive Touch Screen
Buttons in PROGMEM
Dynamic Text LAbels in PROGMEM

One change that affects other parts is that FindElemByCoord reguires the GUI object as a parameter

### CODE REVIEW

**Comment by ImpulseAdventure** [comment]
Thanks @nanokatz -- this is great!

Note: It appears that some of your forked repo may be sourced from earlier versions of GUIslice (prior to b29702b) so I can't perform a direct merge without losing recent commits & pull requests.

I may have overlooked an easier way to handle the selective merge, but for now I have performed a manual 3-way merge between my latest code (b29702b) and your PR, in addition to reverting some customizations in `GUIslice_config.h` that were specific to your instantiation. I then created a branch `nanokatz_02c0ab2` with these updates, starting from your commit 02c0ab2.

Once I have done some basic testing with this branch, I intend to merge it as a new pull request.

Thanks!

**Comment by nanokatz** [comment]
Thats entirely possible. As I said I did the devel with an earlier version (from around Sept I think) I tried to do the manual merge myself but guess I didn't pay close enough attention!

**Comment by ImpulseAdventure** [comment]
Not a problem at all -- I think I've completed the merge now so I'm good to begin testing.

In a later update, I plan to revise the `arduino_min` examples to demonstrate the use of your Flash-based elements. Your feature enhancement will be incredibly useful for Arduino users of GUIslice, so this contribution is greatly appreciated.

**Comment by nanokatz** [comment]
Yeah as I said having the buttons in PROGMEM is what made it really usable for me. If I have the time I plan to try and get the memory usage further down. Ideally I'd love to have it possible to have all the elements in progmem and only items that change (text, glow, etc) in RAM.

**Pull request merged**
